import type { Metadata } from "next";
import "./globals.css";
import { SettingsProvider } from "@/contexts/SettingsContext";
import { SocketProvider } from "@/contexts/SocketContext";
import { ToastProvider } from "@/contexts/ToastContext";
import { ConfirmDialogProvider } from "@/components/ui/confirm-dialog";
import SettingsModal from "@/components/settings/SettingsModal";
import RealtimeToastBridge from "@/components/RealtimeToastBridge";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <SettingsProvider>
          <SocketProvider>
            <ToastProvider>
              <ConfirmDialogProvider>
                {children}
                <RealtimeToastBridge />
                <SettingsModal />
              </ConfirmDialogProvider>
            </ToastProvider>
          </SocketProvider>
        </SettingsProvider>
      </body>
    </html>
  );
}
